name: Create a pull request on master branch

on:
  workflow_dispatch:
    inputs:
      title:
        required: true
      version:
        description: 'Enter release version label'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Ensure branches exist
        run: |
          git fetch origin
          git checkout master || git checkout -b master origin/master
          git checkout staging || git checkout -b staging origin/staging

      - name: pull-request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "staging"
          destination_branch: "master"
          pr_title: ${{ github.event.inputs.title }} - ${{ github.event.inputs.version }}
          pr_label: ${{ github.event.inputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
